services:
  db:
    image: postgres:17
    container_name: checkpoint-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: checkpoint_db
      POSTGRES_USER: checkpoint_user
      POSTGRES_PASSWORD: changeme123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: checkpoint-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@checkpoint.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
