# Generated by Django 6.0.2 on 2026-02-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestItem',
        ),
    ]
