# Generated by Django 6.0.2 on 2026-02-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmembership',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
