# Generated by Django 6.0.2 on 2026-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0003_timeclock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
