# Generated by Django 6.0.2 on 2026-03-07 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0004_alter_businessmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='qr_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
