# Generated by Django 6.0.2 on 2026-03-07 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0005_businessmembership_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='qr_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
