# Generated by Django 6.0.2 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0007_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
